// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwIF3IEYoJ-wkoAS0Oj1a-c1wfYfyEHiA',
    appId: '1:1097403188692:android:dccabe6f70a05a37b68241',
    messagingSenderId: '1097403188692',
    projectId: 'reveduc-5a5b9',
    storageBucket: 'reveduc-5a5b9.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7T16Mia75OG7QPQe7wVOWQs4ccpB-7YE',
    appId: '1:1097403188692:web:4a46bd22fe9da3b4b68241',
    messagingSenderId: '1097403188692',
    projectId: 'reveduc-5a5b9',
    authDomain: 'reveduc-5a5b9.firebaseapp.com',
    storageBucket: 'reveduc-5a5b9.firebasestorage.app',
    measurementId: 'G-7W56TD5P10',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbYUkHG6d_tpRy3ROuqx2vojYP4IGRJiM',
    appId: '1:1097403188692:ios:e51f242c6ad96b08b68241',
    messagingSenderId: '1097403188692',
    projectId: 'reveduc-5a5b9',
    storageBucket: 'reveduc-5a5b9.firebasestorage.app',
    iosBundleId: 'com.reveduc.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7T16Mia75OG7QPQe7wVOWQs4ccpB-7YE',
    appId: '1:1097403188692:web:88a0657bc5b15f28b68241',
    messagingSenderId: '1097403188692',
    projectId: 'reveduc-5a5b9',
    authDomain: 'reveduc-5a5b9.firebaseapp.com',
    storageBucket: 'reveduc-5a5b9.firebasestorage.app',
    measurementId: 'G-2XGBT6V7EC',
  );
}
